"""
auto_sync.py — Fully automated LeetCode → GitHub sync
-------------------------------------------------------
• Reads your LeetCode session cookies directly from Chrome (no manual copying)
• Reads your GitHub token from ~/.leetcode_sync (one-time setup)
• Incremental scrape — only fetches new problems, re-checks existing ones for updated solutions
• Incremental upload — only pushes files whose content changed

FIRST-TIME SETUP (run once):
  python3 auto_sync.py --setup

EVERY SUBSEQUENT RUN:
  python3 auto_sync.py
"""

import os
import sys
import subprocess
import argparse
import json

# ── Config ────────────────────────────────────────────────────────────────────

CREDENTIALS_FILE = os.path.expanduser("~/.leetcode_sync")
SCRIPT_DIR       = os.path.dirname(os.path.abspath(__file__))
CHROME_COOKIES_DB = os.path.expanduser(
    "~/Library/Application Support/Google/Chrome/Default/Cookies"
)

# ── One-time setup ────────────────────────────────────────────────────────────

def setup():
    print("=" * 60)
    print("  LeetCode Sync — First-Time Setup")
    print("=" * 60)
    print()
    print("This stores your GitHub token in ~/.leetcode_sync")
    print("LeetCode cookies will be read automatically from Chrome.")
    print()

    print("To create a token: https://github.com/settings/tokens/new")
    print("  → Note: leetcode-sync  |  Expiration: No expiration  |  Scope: repo")
    print()
    github_token = input("Paste your GitHub Personal Access Token (ghp_...): ").strip()
    if not github_token.startswith("ghp_"):
        print("⚠️  Token doesn't look right (should start with ghp_). Saving anyway.")

    creds = {"github_token": github_token}
    with open(CREDENTIALS_FILE, "w") as f:
        json.dump(creds, f)
    os.chmod(CREDENTIALS_FILE, 0o600)

    print(f"\n✅ Saved to {CREDENTIALS_FILE}")
    print("   Run  python3 auto_sync.py  any time to sync.\n")


def load_github_token():
    if not os.path.exists(CREDENTIALS_FILE):
        print("❌ No credentials found. Run first-time setup:")
        print("     python3 auto_sync.py --setup")
        sys.exit(1)
    with open(CREDENTIALS_FILE) as f:
        creds = json.load(f)
    token = creds.get("github_token", "")
    if not token:
        print("❌ GitHub token missing in ~/.leetcode_sync. Re-run --setup.")
        sys.exit(1)
    return token


# ── Chrome cookie extraction ──────────────────────────────────────────────────

def get_leetcode_cookies():
    """Extract LEETCODE_SESSION and csrftoken from Chrome using pycookiecheat."""
    try:
        from pycookiecheat import chrome_cookies
        cookies = chrome_cookies("https://leetcode.com")
        session = cookies.get("LEETCODE_SESSION")
        csrf    = cookies.get("csrftoken")
        return session, csrf
    except Exception as e:
        print(f"⚠️  pycookiecheat error: {e}")
        return None, None


# ── Main sync ─────────────────────────────────────────────────────────────────

def sync():
    print("=" * 60)
    print("  LeetCode → GitHub Sync")
    print("=" * 60)
    print()

    # 1. Load GitHub token (run setup automatically if not configured)
    if not os.path.exists(CREDENTIALS_FILE):
        print("👋 First time? Let's do a quick one-time setup.")
        print()
        setup()
        print()
    github_token = load_github_token()
    print("✅ GitHub token loaded.")

    # 2. Auto-read LeetCode cookies from Chrome
    print("🔍 Reading LeetCode cookies from Chrome...")
    session, csrf = get_leetcode_cookies()

    if not session or not csrf:
        print("❌ Could not read LeetCode cookies from Chrome.")
        print("   Make sure you're logged in to leetcode.com in Chrome.")
        print()
        print("   Or paste them manually:")
        session = input("   LEETCODE_SESSION: ").strip()
        csrf    = input("   csrftoken: ").strip()

    if not session or not csrf:
        print("❌ No credentials available. Exiting.")
        sys.exit(1)

    print("✅ LeetCode cookies loaded.")

    # 3. Write config.py
    config_path = os.path.join(SCRIPT_DIR, "config.py")
    config_content = f'''# Auto-generated by auto_sync.py — do not edit manually
LEETCODE_SESSION = "{session}"
CSRF_TOKEN       = "{csrf}"
LIST_SLUG        = "n4zbe2xg"
GITHUB_TOKEN     = "{github_token}"
GITHUB_USERNAME  = "debneilroy"
REPO_NAME        = "leetcode-solutions"
REPO_PRIVATE     = False
OUTPUT_DIR       = "output"
'''
    with open(config_path, "w") as f:
        f.write(config_content)
    print("✅ config.py written.")

    # 4. Run the sync
    print()
    os.chdir(SCRIPT_DIR)
    result = subprocess.run([sys.executable, "run.py"])

    # 6. Clear credentials from config.py after upload
    with open(config_path, "w") as f:
        f.write("""# Credentials cleared after sync. Run auto_sync.py to re-sync.
LEETCODE_SESSION = "PASTE_YOUR_LEETCODE_SESSION_COOKIE_HERE"
CSRF_TOKEN       = "PASTE_YOUR_CSRFTOKEN_COOKIE_HERE"
LIST_SLUG        = "n4zbe2xg"
GITHUB_TOKEN     = "PASTE_YOUR_GITHUB_PERSONAL_ACCESS_TOKEN_HERE"
GITHUB_USERNAME  = "debneilroy"
REPO_NAME        = "leetcode-solutions"
REPO_PRIVATE     = False
OUTPUT_DIR       = "output"
""")
    print("🔒 Credentials cleared from config.py.")

    sys.exit(result.returncode)


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Automated LeetCode → GitHub sync")
    parser.add_argument("--setup", action="store_true", help="One-time credential setup")
    args = parser.parse_args()

    if args.setup:
        setup()
    else:
        sync()
