"""
run.py — Master runner
-----------------------
1. Reads credentials from config.py
2. Scrapes all solved problems from your LeetCode list
3. Saves them locally in output/
4. Generates a repo README index
5. Creates a GitHub repo and uploads everything

Usage:
  pip install requests pycookiecheat
  # config.py is auto-generated by auto_sync.py
  python run.py
"""

import os
import shutil
import sys

# ── Validate config ───────────────────────────────────────────────────────────

try:
    import config
except ImportError:
    print("❌ config.py not found. Make sure it's in the same folder as run.py.")
    sys.exit(1)

PLACEHOLDERS = [
    "PASTE_YOUR_LEETCODE_SESSION_COOKIE_HERE",
    "PASTE_YOUR_CSRFTOKEN_COOKIE_HERE",
    "PASTE_YOUR_GITHUB_PERSONAL_ACCESS_TOKEN_HERE",
    "PASTE_YOUR_GITHUB_USERNAME_HERE",
]

missing = []
for attr in ["LEETCODE_SESSION", "CSRF_TOKEN", "GITHUB_TOKEN", "GITHUB_USERNAME"]:
    val = getattr(config, attr, "")
    if not val or val in PLACEHOLDERS:
        missing.append(attr)

if missing:
    print("❌ Please fill in the following fields in config.py before running:")
    for m in missing:
        print(f"   • {m}")
    sys.exit(1)

# ── Run ───────────────────────────────────────────────────────────────────────

from leetcode_scraper import scrape
from generate_site import generate_site
from github_uploader import upload_all, build_repo_readme

OUTPUT_DIR = os.path.abspath(config.OUTPUT_DIR)
os.makedirs(OUTPUT_DIR, exist_ok=True)

print("=" * 60)
print("  LeetCode → GitHub Sync")
print("=" * 60)
print()

# Step 1: Scrape (fetches new problems; re-checks existing ones for updated solutions)
saved, skipped = scrape(
    leetcode_session=config.LEETCODE_SESSION,
    csrf_token=config.CSRF_TOKEN,
    list_slug=config.LIST_SLUG,
    output_dir=OUTPUT_DIR,
    force_refresh=os.environ.get("FORCE_REFRESH_README") == "1",
)

# Step 1b: Copy manually-authored "Unknown" problems (not on LeetCode, so the
# scraper can't find them) from the git-tracked unknown/ folder into output/
UNKNOWN_SRC = os.path.join(os.path.dirname(os.path.abspath(__file__)), "unknown")
if os.path.isdir(UNKNOWN_SRC):
    shutil.copytree(UNKNOWN_SRC, os.path.join(OUTPUT_DIR, "Unknown"), dirs_exist_ok=True)

# Step 2: Generate LeetCode-style HTML site
generate_site(OUTPUT_DIR)

# Step 3: Build repo README (regenerated each sync to reflect new problems)
print("📝 Generating repo README...")
repo_url = f"https://github.com/{config.GITHUB_USERNAME}/{config.REPO_NAME}"
readme_content = build_repo_readme(OUTPUT_DIR, repo_url)
readme_path = os.path.join(OUTPUT_DIR, "README.md")
with open(readme_path, "w", encoding="utf-8") as f:
    f.write(readme_content)

# Step 4: Upload everything to GitHub
print()
repo_link = upload_all(
    github_token=config.GITHUB_TOKEN,
    github_username=config.GITHUB_USERNAME,
    repo_name=config.REPO_NAME,
    output_dir=OUTPUT_DIR,
    private=config.REPO_PRIVATE,
)

pages_url = f"https://debneilroy.github.io/leetcode-solutions/"
print(f"\n🎉 Done! Repo: {repo_link}")
print(f"\n🌐 Enable GitHub Pages to get your live site:")
print(f"   {repo_link} → Settings → Pages → Source: main → / (root)")
print(f"   Then visit: {pages_url}\n")
